[IMP] Field Services Global
GoShop-Energy/field-service pull request #1
Opened 2023-12-02 16:28 UTC by iambenkis

### Specification

#### 1. Contact form modification
Add a new address type: "Service Location"
Include a star button to display the count of "Service Locations" associated with each company or individual.
Fields for "Service Location" info:
Contact Name
+ phone 
+ email
Equipment name
Address (street, city, country, the regular one)
Type: select (Solar, Water Heater, Genset, Air Conditioning, other) if other is selected, a text field to write i)
Internal Notes

#### 2. Sales Order (SO) updates
Integrate the "Service Location" field below the other address
Add a "Services Instructions" tab:
This tab is visible only if a service product creating a task is added to the SO
field is an HTML one
Make the "Service Instructions" mandatory

#### 3. Task generation and Management
On the task generate upon SO validation, add a tag by default, the name of the Warehouse linked to the Sale Order.
Duplicate the content from "Services Instructions" into the task's description.
Below the instructions, include a table listing materials (product name, product description, and quantity ordered).
Add a "Service Location" field on the task (below other address).
Add a star button linked to the deliveries + display delivery status on task.
Display the task ID as a read-only field .
On the report, display the task ID.

2023-12-05 06:59 UTC, sbuhl requested changes
@iambenkis  first round of review.

2023-12-05 06:59 UTC, sbuhl commented on models/res_partner.py
> +    field_service_type = fields.Selection([
@iambenkis  should be mandatory

2023-12-05 06:59 UTC, sbuhl commented on models/res_partner.py
> +                            help="Service Location: This field represents the type of service.")
@iambenkis  "Use to identify local service sites of the customer."

2023-12-05 06:59 UTC, sbuhl commented on models/res_partner.py
> +    other_description = fields.Char('Other Description')
@iambenkis  "Site Description"

2023-12-05 06:59 UTC, sbuhl commented on models/res_partner.py
> +            self.other_description = ''
@iambenkis  is it necessary? Why not just hide it in XML?

2023-12-05 06:59 UTC, sbuhl commented on models/sale_order.py
> +    instruction = fields.Html(string='Service Location')
@iambenkis  String= "Service Instructions"

2023-12-05 06:59 UTC, sbuhl commented on models/sale_order.py
> +        string="Product")
@iambenkis  🤔  something is missing in this model...

2023-12-05 06:59 UTC, sbuhl commented on reports/project_report_views.xml
> +            </h2>
@iambenkis  not the good position. If there is no timesheet, we don't see the Task ID...

2023-12-05 06:59 UTC, sbuhl commented on views/res_partner_views.xml
> +                                    <span>Use four this to organize the contact details of employees of a given company (e.g. CEO, CFO, ...).</span>
@iambenkis  are we forced to replace the whole file? 
Can't you target an element more precisely to only add what's missing?

2023-12-05 12:40 UTC, sbuhl commented on models/project.py
> +    tag_ids = fields.Many2many('project.tags', string='Tags', compute='_compute_default_tags', readonly=False)
@iambenkis  look how the value are get from the SO to create the name, customer, etc
https://github.com/odoo/odoo/blob/3652f90e610a786092236ab6e7ca8b3af3d58248/addons/sale_project/models/sale_order_line.py#L215
Maybe some things to use to create the tags...

2023-12-05 12:43 UTC, iambenkis commented on models/project.py
> +    tag_ids = fields.Many2many('project.tags', string='Tags', compute='_compute_default_tags', readonly=False)
Lemme look at it 👀

2023-12-07 08:08 UTC, sbuhl commented on models/project.py
> +    tag_ids = fields.Many2many('project.tags', string='Tags', compute='_compute_default_tags', readonly=False)
Hello @iambenkis,

I've recently conducted a test using Odoo's default method, and I'm pleased to report that the system is effectively handling the tags (add or remove tags). Could you take a closer look and explore how we might adapt your code to ensure seamless operation within Odoo framework?

2023-12-12 09:26 UTC, sbuhl requested changes

2023-12-12 09:26 UTC, sbuhl commented on models/res_partner.py
> +    field_service_type = fields.Selection([
@iambenkis  do you read my comments?

2024-01-10 14:02 UTC, sbuhl commented on models/res_partner.py
> +                            help="Service Location: This field represents the type of service.")
@iambenkis  ??

2024-01-10 14:02 UTC, sbuhl commented on models/res_partner.py
> +    field_service_type = fields.Selection([
@iambenkis  ??

2024-01-10 14:02 UTC, sbuhl commented on models/res_partner.py
> +    other_description = fields.Char('Other Description')
@iambenkis  ??

2024-01-11 07:48 UTC, sbuhl commented on views/res_partner_views.xml
> +                            <img alt="Location image" src="https://drive.google.com/uc?export=view&amp;id=1Gwtc-LN18S89xUfLrUAYtJQpArr-pa--" attrs="{'invisible': [('type', '!=', 'field_service')]}"/>
@iambenkis  pourquoi ne pas utiliser ce qui est dans le folder static?

2024-01-11 11:09 UTC, sbuhl requested changes
Hello @iambenkis 
One final review for nitpicking and code convention is needed. Please install a linter to avoid these types of comments in the future.

I'm still waiting for your point of view regarding the addresses.

2024-01-11 11:09 UTC, sbuhl commented on models/sale_order.py
> +from odoo.tools import float_is_zero, format_amount, format_date, html_keep_url, is_html_empty
Those are unused.

2024-01-11 11:09 UTC, sbuhl commented on models/sale_order.py
> +from odoo import models, fields, api, _
is "_" used?

2024-01-11 11:09 UTC, sbuhl commented on models/sale_order.py
> +class SaleOrder(models.Model):
add space before

2024-01-11 11:09 UTC, sbuhl commented on models/sale_order.py
> +                self.write({'child_id': ''})
Final new line missing

2024-01-11 11:09 UTC, sbuhl commented on models/res_partner.py
> +from odoo import fields, models, api
# -*- coding: utf-8 -*-
Missing, or is it no more needed? Can you check in the doc?

2024-01-11 11:09 UTC, sbuhl commented on models/res_partner.py
> +from odoo import fields, models, api
+ "api" is not used.

2024-01-11 11:09 UTC, sbuhl commented on models/res_partner.py
> +                ])
Missing last white line

2024-01-11 11:09 UTC, sbuhl commented on models/project.py
> +from odoo import api, fields, models
# -*- coding: utf-8 -*-
 missing

2024-01-11 11:09 UTC, sbuhl commented on models/project.py
> +
remove one line

2024-01-16 07:54 UTC, sbuhl approved these changes

2024-01-16 07:54 UTC, merged